// Code generated by web3tool/abigen. DO NOT EDIT.
// Hash: 3f1af52b391dcf1991b5cee7468a69f382cfa0f819eaff85474464c969fe7ea9
// Version: 0.1.1
package testdata

import (
	"fmt"
	"math/big"

	"github.com/yellomoon/web3tool"
	"github.com/yellomoon/web3tool/contract"
	"github.com/yellomoon/web3tool/jsonrpc"
)

var (
	_ = big.NewInt
	_ = jsonrpc.NewClient
)

// Testdata is a solidity contract
type Testdata struct {
	c *contract.Contract
}

// NewTestdata creates a new instance of the contract at a specific address
func NewTestdata(addr web3tool.Address, opts ...contract.ContractOption) *Testdata {
	return &Testdata{c: contract.NewContract(addr, abiTestdata, opts...)}
}

// calls

// CallBasicInput calls the callBasicInput method in the solidity contract
func (t *Testdata) CallBasicInput(block ...web3tool.BlockNumber) (retval0 *big.Int, retval1 web3tool.Address, err error) {
	var out map[string]interface{}
	var ok bool

	out, err = t.c.Call("callBasicInput", web3tool.EncodeBlock(block...))
	if err != nil {
		return
	}

	// decode outputs
	retval0, ok = out["0"].(*big.Int)
	if !ok {
		err = fmt.Errorf("failed to encode output at index 0")
		return
	}
	retval1, ok = out["1"].(web3tool.Address)
	if !ok {
		err = fmt.Errorf("failed to encode output at index 1")
		return
	}
	
	return
}

// txns

// TxnBasicInput sends a txnBasicInput transaction in the solidity contract
func (t *Testdata) TxnBasicInput(val1 web3tool.Address, val2 *big.Int) (contract.Txn, error) {
	return t.c.Txn("txnBasicInput", val1, val2)
}

// events

func (t *Testdata) EventBasicEventSig() web3tool.Hash {
	return t.c.GetABI().Events["EventBasic"].ID()
}
