name: Unit tests
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    name: Go test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install ethers testcases
        run: cd ./testcases && npm install
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: "1.18.1"
      - name: "Setup"
        run: ./scripts/setup-ci.sh
      - name: "Setup geth"
        run: ./scripts/setup-geth.sh
      - name: Go test
        run: go test -v ./...
